const activityEnum = {
  CREATED_QUESTION: 'CREATED_QUESTION',
  EDITED_QUESTION: 'EDITED_QUESTION',
  CREATED_ANSWER: 'CREATED_ANSWER',
  EDITED_ANSWER: 'EDITED_ANSWER',
  ACCEPTED_ANSWER: 'ACCEPTED_ANSWER',
  LIKED: 'LIKED',
  BOOKMARKED: 'BOOKMARKED',
}

module.exports = activityEnum;